### ISSUE TITLE
Add timeline UI for education 

### ISSUE THREAD

**Issue by bislara** [bislara/project-enigma#10]
## Description
Add a proper timeline section for education in About me page. Make something similar to the below pic

![image](https://user-images.githubusercontent.com/35392585/135707648-dc7b6c0e-1ea9-40aa-a07c-fbfd5a3e6daa.png)

## Technologies and Languages
React js

**Comment by ankitgauri26** [comment]
@bislara - I can add the timeline using ant design library (https://ant.design/components/timeline/) . Please assign it to me.

**Comment by AbhiramKrishna88** [comment]
I just added the timeline 
![image](https://user-images.githubusercontent.com/66553902/135710494-0c6b7550-7550-4a45-b85b-c33f7d904711.png)
Need changes? I am listening ... 😄

**Comment by bislara** [comment]
@ankitgauri26 This whole project has been done from scratch and doesn't use any UI libraries. So, doing it from scratch will be preferred to including ant design. So, let me know if you can proceed with this.

@AbhiramKrishna88 Good job mate. It looks good. But, I choose first come first assign. So, if @ankitgauri26 is not able to continue, then you can create PR. Also, let me know how you did this.

**Comment by AbhiramKrishna88** [comment]
@bislara I did this from scratch using pure HTML CSS and added it into react.

**Comment by bislara** [comment]
> @bislara I did this from scratch using pure HTML CSS and added it in to react.

Oh, that's good to hear. Please wait some time till @ankitgauri26 replies. Or else I will assign you this.

**Comment by ankitgauri26** [comment]
@bislara  - Thank you for considering me. But i would recommend you to take @AbhiramKrishna88 work as he has already done it. Let's save developer's time :)

**Comment by bislara** [comment]
Cool. @AbhiramKrishna88 you can go ahead and create a PR
