### ISSUE TITLE
Custom scrollbar

### ISSUE THREAD

**Issue by KarishmaVanwari** [bislara/project-enigma#17]
Adding a custom scrollbar would improve the look of the website.

**Comment by KarishmaVanwari** [comment]
Hey @bislara  can I work on this issue as a part of Hacktoberfest 2021, if it's okay with you?
Also, you can let me know your colour preferences, if any.

**Comment by bislara** [comment]
Yes, that okay. Go ahead. There is no preference for me. Choose the one which suits the most, maybe some complementary colors with respect to the body of the page.

**Comment by KarishmaVanwari** [comment]
> Yes, that okay. Go ahead. There is no preference for me. Choose the one which suits the most, maybe some complementary colors with respect to the body of the page.

Yeah, sure. Could you please add hacktoberfest label?

**Comment by bislara** [comment]
The label is there in the repo. No need to add in the issue. In Pr, I will add the hacktoberfest-accepted label

**Comment by KarishmaVanwari** [comment]
Okay

**Comment by KarishmaVanwari** [comment]
@bislara do have a look at #18 and also add hacktoberfest-accepted label if it seems okay.
