### ISSUE TITLE
Add achievement section

### ISSUE THREAD

**Issue by bislara** [bislara/project-enigma#4]
## Description
Add a section having attractive cards for achievements. Details like position, competition name, descriptions, etc should be present in the card

Put dummy data for now. I will replace it with the original one.

## Technologies and Languages

- Reactjs, css

**Comment by danmolloy** [comment]
Hi bislara,

I would like to help with this issue. Could you please assign it to me?

**Comment by bislara** [comment]
Sure. Go ahead. Let me know if you need any details

**Comment by danmolloy** [comment]
Great! I'll get to work.

**Comment by danmolloy** [comment]
Hi Biswajeet,

I've just a couple of questions for you.

Are you hoping for the achievement cards to be on a separate Achievements page (with a link in the navbar), or another section on the experience page?

Also, I see you have some cards on the experience page. Should I take those as an example to follow?

Thanks, Dan

**Comment by bislara** [comment]
hey @danmolloy 
1. I need a different page for the achievements section and yes add the link in the navbar also. 
2. You can take some guidance from that but don't use the exact same one. Make it something different. Thats the purpose of this issue.
