### ISSUE TITLE
Add Page Loader

### ISSUE THREAD

**Issue by bislara** [bislara/project-enigma#9]
## Description
Add an amazing page loader which will continue till the page renders completely (at least till the images are loaded). 
Add this to every page. 

## Technologies and Languages
React js

**Comment by wesley3295** [comment]
There is no API calls in your portfolio. You are using hard coded data in your assets to populate your projects and skills. Not sure how to implement a loading screen with no promises, unless relative file paths are considered promises? I might be a little inexperienced, but I've only ever added loading screens to projects when there is Asynchronous JS involved.

**Comment by bislara** [comment]
Hey, in this case, it's fine if there are no promises. You can simply add a preloader. Try some look around for the rending part, that's optional. But look for some innovative and attractive preloader.

**Comment by AbhiramKrishna88** [comment]
I could add a waiting time like a second before the contents are shown. More like simulating a fake request. For attractive loader, there are many open-sourced codes. I could use any of that. 

A list of attractive loaders: [Link](https://freefrontend.com/css-loaders/) 🎨

**Comment by bislara** [comment]
Yes, you can go ahead with these loaders. Choose a good-looking one for this project. Let me know about it too. 
Also, it's fine to put a waiting time for now. The project is lightweight, just the images sometimes take a little time. So, we just need to cover up that part.

**Comment by AbhiramKrishna88** [comment]
@bislara simple and clean minimal bouncing ball loading animation. I would be nice if you could suggest me the color/gradient or any further changes u would like.

![image](https://user-images.githubusercontent.com/66553902/135712262-b4a95254-0024-4170-ab81-954389d365be.png)
![image](https://user-images.githubusercontent.com/66553902/135712287-98feb714-a51d-4659-ab88-143aa7568b94.png)
![image](https://user-images.githubusercontent.com/66553902/135712322-873f8d98-0b0f-4425-87d9-140c12a9ec7e.png)
These are some suggestion ⬆️ 

full page view ⬇️ 
![image](https://user-images.githubusercontent.com/66553902/135712405-466d50ed-5374-4fff-857c-a441f54093e0.png)

**Comment by bislara** [comment]
This looks good. Go ahead with the first option, ie the dark green one. Looking forward to see your PR🚀
